<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.assessment.parser.service.FileProcessServiceTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2021-04-15T16:19:20" hostname="ALBERTORIBEIRO" time="1.073">
  <properties/>
  <testcase name="saveEventLogFails_whenJSONIsInvalid()" classname="com.assessment.parser.service.FileProcessServiceTest" time="1.047"/>
  <testcase name="saveEventLogFails_whenFileNotFound()" classname="com.assessment.parser.service.FileProcessServiceTest" time="0.004"/>
  <testcase name="saveEventLogFail_whenIOExceptionIsThrown()" classname="com.assessment.parser.service.FileProcessServiceTest" time="0.012"/>
  <testcase name="saveEventLogSuccessfully_whenRequiredFieldsAreSetOnly()" classname="com.assessment.parser.service.FileProcessServiceTest" time="0.007"/>
  <system-out><![CDATA[13:19:21.192 [Test worker] ERROR com.assessment.parser.service.impl.FileProcessServiceImpl - Error converting the JSON [{"NotValidField":"scsmbstgra", "state":"STARTED", "type":"APPLICATION_LOG", "host":"12345", "timestamp":1491377495212}] to EventDTO, reason [Unrecognized field "NotValidField" (class com.assessment.parser.dto.EventDTO), not marked as ignorable (5 known properties: "host", "state", "type", "id", "timestamp"])
 at [Source: (String)"{"NotValidField":"scsmbstgra", "state":"STARTED", "type":"APPLICATION_LOG", "host":"12345", "timestamp":1491377495212}"; line: 1, column: 19] (through reference chain: com.assessment.parser.dto.EventDTO["NotValidField"])]
13:19:21.197 [Test worker] ERROR com.assessment.parser.service.impl.FileProcessServiceImpl - Error reading file [invalid_logfile.txt], reason [Error converting the JSON [{"NotValidField":"scsmbstgra", "state":"STARTED", "type":"APPLICATION_LOG", "host":"12345", "timestamp":1491377495212}] to EventDTO, reason [Unrecognized field "NotValidField" (class com.assessment.parser.dto.EventDTO), not marked as ignorable (5 known properties: "host", "state", "type", "id", "timestamp"])
 at [Source: (String)"{"NotValidField":"scsmbstgra", "state":"STARTED", "type":"APPLICATION_LOG", "host":"12345", "timestamp":1491377495212}"; line: 1, column: 19] (through reference chain: com.assessment.parser.dto.EventDTO["NotValidField"])]]
13:19:21.207 [Test worker] ERROR com.assessment.parser.service.impl.FileProcessServiceImpl - Provided file [logfileNotExists.txt] doesn't exists, please check the full path of the File
13:19:21.219 [Test worker] ERROR com.assessment.parser.service.impl.FileProcessServiceImpl - Error reading file [logfile.txt], reason [Unexpected Error]
13:19:21.227 [Test worker] INFO com.assessment.parser.service.impl.FileProcessServiceImpl - File [logfile.txt] successfully parsed in [3] miliseconds
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
